server:
  port: 8181
  servlet:
    session:
      tracking-modes: cookie
spring:
  application:
    name: java_mybatisplus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jdbc_test
    username: root
    password: yonghwa
