server:
  port: 8181
spring:
  application:
    name: java_boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jdbc_test
    username: root
    password: yonghwa
  security:
    user:
      name: admin
      password: 123456